import IndisputableMonolith.Foundation.NothingToDistinction
import IndisputableMonolith.Foundation.TMinus1ToT8Bridge
import IndisputableMonolith.Foundation.CircleWindingChain
import IndisputableMonolith.Foundation.PhiForcing
import IndisputableMonolith.Foundation.AlexanderDuality
import IndisputableMonolith.Foundation.DimensionForcing
import IndisputableMonolith.Foundation.GapDerivation
import IndisputableMonolith.RecognitionCore
import IndisputableMonolith.Foundation.PrimitiveRecognitionCalculus.QuotientSelection
import IndisputableMonolith.Cost.FunctionalEquation
import IndisputableMonolith.CostUniqueness
import IndisputableMonolith.Constants
import IndisputableMonolith.Constants.AlphaDerivation
import IndisputableMonolith.Patterns.GrayCycle
import IndisputableMonolith.Masses.TorsionForcing
import IndisputableMonolith.Gravity.ILG
import IndisputableMonolith.Gravity.ParameterizationBridge
import IndisputableMonolith.Gravity.GravityParameters
import IndisputableMonolith.Gravity.DerivedFactors
import IndisputableMonolith.Gravity.Rotation
import IndisputableMonolith.Verification.DimensionalRigidity
import IndisputableMonolith.Foundation.PrimitiveDistinction
import IndisputableMonolith.Verification.T5.LedgerCost
import IndisputableMonolith.Cosmology.EtaBPrefactorDerivation
import IndisputableMonolith.Masses.Verification

/-!
# IndisputableMonolith (paper slice)

Root module for the paper-support slice cited in
`papers/RS_v1_rewrite/rs_v1_fop.tex` (Foundations of Physics intro).
It imports every module whose declarations appear in the verification
appendix, plus their transitive dependencies.
-/
